name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies (backend)
        run: |
          cd backend
          npm install

      - name: Run tests (backend)
        run: |
          cd backend
          npm test

deploy:
  runs-on: self-hosted
  needs: build
  if: github.ref == 'refs/heads/main'
  environment: prod

  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to EC2
      run: |
        cd ~/sampleapp_IFQ636_I-Ching-Chang
        git pull origin main
        cd backend
        npm install
        pm2 restart backend
        cd ../frontend
        npm install
        npm run build
