name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    environment: prod

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install

      - name: Run Backend Tests
        run: |
          cd backend
          npm test

      - name: Create .env File
        run: |
          echo "MONGO_URL=${{ secrets.MONGO_URL }}" > ~/sampleapp_IFQ636_I-Ching-Chang/backend/.env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> ~/sampleapp_IFQ636_I-Ching-Chang/backend/.env
          echo "PORT=${{ secrets.PORT }}" >> ~/sampleapp_IFQ636_I-Ching-Chang/backend/.env

      - name: Restart PM2
        run: pm2 restart backend
